
# ! Dependency injection example
# from fastapi import Depends

# class MistralClient:
#     def __init__(self, api_key: str):
#         self.api_key = api_key

#     def generate_course(self, prompt: str):
#         # Call Mistral API here
#         return {
#             "course_title": "Mock Course",
#             "description": "Generated by Mistral",
#             "lessons": []
#         }

# # Dependency
# def get_mistral_client():
#     client = MistralClient(api_key="YOUR_API_KEY")
#     try:
#         yield client
#     finally:
#         # Cleanup if needed (e.g., close connections)
#         pass


# ! Usage in endpoint
# def generate_course(mistral: MistralClient = Depends(get_mistral_client)):
#     prompt = "Generate a beginner algorithm course..."
#     return mistral.generate_course(prompt)