FROM    node:24-alpine AS builder

WORKDIR /app

COPY    package*.json ./

RUN     npm install

COPY    . .

RUN     npm run build

FROM    node:24-alpine

WORKDIR /app

RUN     apk add --no-cache iputils

COPY    --from=builder /app ./

EXPOSE  3000

CMD     ["npm", "start"]