import type { Metadata } from "next";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Providers } from "./Providers";

const queryClient = new QueryClient();

export const metadata: Metadata = {
    title: "Understand.io",
    description: "Generated by create next app",
};

export default function RootLayout({ children }:
    Readonly<{ children: React.ReactNode; }>) {

    return (
        <html lang="en">
            <body>
                <Providers>
                    {children}
                </Providers>
            </body>
        </html>
    );
}