services:
  frontend:
    container_name: frontend
    build: ./frontend
    env_file:
      - .env
    networks:
      - my_network
    depends_on:
      - backend
    ports:
      - "3000:3000"

  backend:
    container_name: backend
    build: ./backend
    restart: always
    env_file:
      - .env
    networks:
      - my_network
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    container_name: db
    image: postgres:17.6
    restart: always
    env_file:
      - .env
    networks:
      - my_network
    ports:
      - "5432:5432"

networks:
  my_network:
    driver: bridge