# import os
# from fastapi import Depends
# from mistralai import Mistral
# from functools import lru_cache
# from app.backend.app.core.config import app_env_settings as settings


# @lru_cache
# def get_mistral_sdk_client() -> Mistral:
#     return Mistral(api_key=settings.mistral_api_key)


# class MistralClient:
#     def __init__(self, client: Mistral) -> None:
#         self.model = "mistral-medium-latest"
#         self.client = client

#     def generate_course(self, prompt: str):
#         chat_response = self.client.chat.complete(
#             model=self.model,
#             messages=[
#                 {
#                     "role": "user",
#                     "content": prompt,
#                 },
#             ],
#         )
#         return chat_response
#         # return {
#         #     "course_title": "Mock Course",
#         #     "description": "Generated by Mistral",
#         #     "lessons": [],
#         # }


# def get_mistral_client(
#     client: Mistral = Depends(get_mistral_sdk_client),
# ) -> MistralClient:
#     return MistralClient(client)
